"""
Generates and solves random linear programming standard maximum
problem test cases with exact arithmetic.

Generates random LP maximization instances using NumPy, converts the data to
SymPy Rationals for exact fractional solving (via `lpmax`), and outputs the
results to separate text files.

Outputs:
    genInput.txt: Contains the problem instances formatted as custom strings.
    genExpectedOutput.txt: Contains the solutions.

Source: Refactored from an initial prototype generated by Google Gemini.
"""

import argparse
import numpy as np
from sympy import Rational, symbols
from sympy.solvers.simplex import lpmax, UnboundedLPError, InfeasibleLPError


def instance_string(a, b, c):
    """Converts lp-instance into string."""

    instance = "{["
    for i, row in enumerate(a):
        sep = "," if i < len(a) - 1 else ""
        instance += f"{row}{sep}"

    instance += f"],{b},{c}" + "}"

    return instance


def generate_lp_instances(num_instances=1, num_variables=3, num_constraints=3):
    """Generates random lp-instances."""
    instances = []

    for _ in range(0, num_instances):
        a = np.random.randint(-50, 100, size=(num_constraints, num_variables)).tolist()
        b = np.random.randint(-30, 150, size=num_constraints).tolist()
        c = np.random.randint(-10, 50, size=num_variables).tolist()
        instances.append((a, b, c))

    return instances


def construct_sympy_instance(a_rational, b_rational, c_rational):
    """Constructs sympy instance from lp-instance"""
    num_vars = len(c_rational)
    x = symbols(f"x0:{num_vars}")

    # Construct algebraic objective function: c0*x0 + c1*x1 + ...
    objective = sum(c_rational[j] * x[j] for j in range(num_vars))

    # Construct algebraic inequalities: a0*x0 + a1*x1 <= b0
    constraints = []
    for i, comp in enumerate(b_rational):
        lhs = sum(a_rational[i][j] * x[j] for j in range(num_vars))
        constraints.append(lhs <= comp)

    for var in x:
        constraints.append(var >= 0)

    return objective, constraints


def solve_instance_sympy(a, b, c):
    """Solves lp-instance using sympy.lpmax."""

    num_vars = len(c)
    x = symbols(f"x0:{num_vars}")

    a_rational = [[Rational(x) for x in row] for row in a]
    b_rational = [Rational(x) for x in b]
    c_rational = [Rational(x) for x in c]

    objective, constraints = construct_sympy_instance(
        a_rational, b_rational, c_rational
    )

    try:
        optimal_val, optimal_x_dict = lpmax(objective, constraints)

        # Format output dictionary back to an ordered list matching x0, x1, x2...
        # SymPy assumes variables are >= 0 by default in lpmax
        optimal_x_list = [optimal_x_dict.get(var, 0) for var in x]

        return [optimal_x_list, optimal_val]

    except (UnboundedLPError, InfeasibleLPError) as e:
        return [None, f"{e}"]


def write_to_file(path, contents):
    """Writes contents to path as seperate lines."""
    with open(path, "w", encoding="utf-8") as f_output:
        for item in contents:
            f_output.write(f"{str(item)}\n")


def main():
    """The main part of the script."""
    args_parser = argparse.ArgumentParser()
    args_parser.add_argument("arg1", type=int, help="Instance count")
    args = args_parser.parse_args()
    instance_count = args.arg1

    instances = []
    for _ in range(instance_count):
        vars_count = np.random.randint(4, 12)
        const_count = np.random.randint(4, 12)
        instances.extend(generate_lp_instances(1, vars_count, const_count))

    instance_strings = [instance_string(*instance) for instance in instances]
    instance_solutions = [(solve_instance_sympy(*instance)) for instance in instances]

    write_to_file("genInput.txt", instance_strings)
    write_to_file("genExpectedOutput.txt", instance_solutions)


# Usage: python test_case_generator.py 5
if __name__ == "__main__":
    main()
